### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by KGalaffu** [lucid-eleven/nft-metadata-api-proxy#1]
Hello, I would like to implement your api to my project but I face some small questions, would you have discord to discuss if possible? 

Thanking you for your repo !

**Comment by lucid-eleven** [comment]
Sure, eleven#7059 is my discord id

**Comment by KGalaffu** [comment]
Discord tells me that you do not accept requests

I leave you my id: 

Fufette#2276

Thanks
