### ISSUE TITLE
Problem: Image URL can still expose all images

### ISSUE THREAD

**Issue by cdc-Hitesh** [lucid-eleven/nft-metadata-api-proxy#2]
the `image` parameter of the metadata returned from already minted NFT can give assumable image directory links.

@lucid-eleven

**Comment by lucid-eleven** [comment]
You should not bulk upload all your images in a single folder, you should instead upload each one individually

**Comment by mannutech** [comment]
Doesn't that mean the URL has to be updated on smart contract individually for every NFT? Because it won't be deterministic any more.

**Comment by lucid-eleven** [comment]
No, your metadata json files are still uploaded in a single folder, but this proxy will hide the CID of that folder.

Your concern is about the IPFS hash for the images, so my point is the images themselves should be uploaded individually, and the CID for each image should be put into each corresponding json file
