### ISSUE TITLE
Token doesn't exist...

### ISSUE THREAD

**Issue by TheMrRaGe** [lucid-eleven/nft-metadata-api-proxy#3]
but it does... is this only a mainnet app or would it work in Rinkeby??  Also..... ^^^ Why it do that?

**Comment by lucid-eleven** [comment]
You're going to have to provide a lot more details.

What's the contract address, what's the token id you're checking?  What's your app url?

**Comment by TheMrRaGe** [comment]
0x19d0c93dCA11111146f41817F8b0f81A538dc5d7 (Boom)
12 (Boom)
https://projectdudes.herokuapp.com/ (and Boom) lol

**Comment by TheMrRaGe** [comment]
one second... I may have figured out what i messed up. i took it down to redeploy

**Comment by TheMrRaGe** [comment]
yea, still having the issue. I can get it as far as showing the "Cannot get /" and it shows the total supply correct. but errors out on the 12.json. lol it's probably me missing the simplest thing too. XD

**Comment by TheMrRaGe** [comment]
new app is https://pd-proxy.herokuapp.com/

**Comment by lucid-eleven** [comment]
It's probably because my code assumes that the tokenId query parameter is a number, i.e. it doesn't have the .json extension.  That's the common way that most projects do it, but I see that your tokenURI function in your smart contract appending the .json extension at the end.  

You will either have to modify the code to properly parse the query parameter to account for the .json extension, or change your smart contract to leave it out.

**Comment by TheMrRaGe** [comment]
word ill try taking the extension out.

**Comment by lucid-eleven** [comment]
if you uploaded your files to IPFS with extensions, you'll have to remove those too, so the files should not be named 1.json, 2.json, etc.., they should just be 1, 2, without extensions

**Comment by TheMrRaGe** [comment]
so just to clarify my options are to modify the smart contract and filenames and my alternative is to modify the code itself to account for the extension. lol this should be fun. any suggestions?

**Comment by TheMrRaGe** [comment]
the file names in the directory itself are "1,2,3,4" in ipfs it shows the extension. does that matter? 
sorry for all the questions lol your doing important stuff and I'm just wanting to understand =)

**Comment by lucid-eleven** [comment]
depends on what you're more familiar/comfortable with, it's probably less work to modify the code here, though it's more complex, while the change to remove the extensions is a more simple change but probably more time consuming

**Comment by lucid-eleven** [comment]
> 

I'm not sure what you mean by this question, if the files are just called 1,2,3,4 in the directory, then when you upload the folder to IPFS you'll access them by a URL like `ipfs://hash/1`, if you use `ipfs://hash/1.json` it won't work

**Comment by TheMrRaGe** [comment]
yea i was using the contract for something else and restructured it lolol i totally forgot the extension was there XD I'm going to try each option and see how it goes. I appreciate your time and ill hit you back if i have any more questions 👍

**Comment by TheMrRaGe** [comment]
What do you think about using the token ID and suffix (.json) in Query arg?

**Comment by TheMrRaGe** [comment]
I got it working. Different filename with no .json and changing the contract to URI suffix and leaving it blank was the solution. Thanks again!
